iso_code_country: [
  ["US", "1", "USA", "short_list"],
  ["DZ", "213", "Algeria"],
  ["AD", "376", "Andorra"],
  ["AO", "244", "Angola"],
  ["AI", "1264", "Anguilla"],
  ["AG", "1268", "Antigua & Barbuda"],
  ["AR", "54", "Argentina", "short_list"],
  ["AM", "374", "Armenia"],
  ["AW", "297", "Aruba"],
  ["AU", "61", "Australia", "short_list"],
  ["AT", "43", "Austria", "short_list"],
  ["AZ", "994", "Azerbaijan"],
  ["BS", "1242", "Bahamas", "short_list"],
  ["BH", "973", "Bahrain", "short_list"],
  ["BD", "880", "Bangladesh"],
  ["BB", "1246", "Barbados"],
  ["BY", "375", "Belarus"],
  ["BE", "32", "Belgium", "short_list"],
  ["BZ", "501", "Belize"],
  ["BJ", "229", "Benin"],
  ["BM", "1441", "Bermuda", "short_list"],
  ["BT", "975", "Bhutan"],
  ["BO", "591", "Bolivia", "short_list"],
  ["BA", "387", "Bosnia Herzegovina"],
  ["BW", "267", "Botswana", "short_list"],
  ["BR", "55", "Brazil", "short_list"],
  ["BN", "673", "Brunei"],
  ["BG", "359", "Bulgaria", "short_list"],
  ["BF", "226", "Burkina Faso"],
  ["BI", "257", "Burundi"],
  ["KH", "855", "Cambodia"],
  ["CM", "237", "Cameroon"],
  ["CA", "1", "Canada", "short_list"],
  ["CV", "238", "Cape Verde Islands"],
  ["KY", "1345", "Cayman Islands", "short_list"],
  ["CF", "236", "Central African Republic"],
  ["CL", "56", "Chile", "short_list"],
  ["CN", "86", "China", "short_list"],
  ["CO", "57", "Colombia", "short_list"],
  ["KM", "269", "Comoros"],
  ["CG", "242", "Congo"],
  ["CK", "682", "Cook Islands"],
  ["CR", "506", "Costa Rica", "short_list"],
  ["HR", "385", "Croatia"],
  ["CU", "53", "Cuba"],
  ["CY", "90392", "Cyprus North"],
  ["CY", "357", "Cyprus South"],
  ["CZ", "42", "Czech Republic", "short_list"],
  ["DK", "45", "Denmark", "short_list"],
  ["DJ", "253", "Djibouti"],
  ["DM", "1809", "Dominica"],
  ["DO", "1809", "Dominican Republic"],
  ["EC", "593", "Ecuador", "short_list"],
  ["EG", "20", "Egypt", "short_list"],
  ["SV", "503", "El Salvador"],
  ["GQ", "240", "Equatorial Guinea"],
  ["ER", "291", "Eritrea"],
  ["EE", "372", "Estonia", "short_list"],
  ["ET", "251", "Ethiopia"],
  ["FK", "500", "Falkland Islands"],
  ["FO", "298", "Faroe Islands"],
  ["FJ", "679", "Fiji"],
  ["FI", "358", "Finland", "short_list"],
  ["FR", "33", "France", "short_list"],
  ["GF", "594", "French Guiana"],
  ["PF", "689", "French Polynesia"],
  ["GA", "241", "Gabon"],
  ["GM", "220", "Gambia"],
  ["GE", "7880", "Georgia"],
  ["DE", "49", "Germany", "short_list"],
  ["GH", "233", "Ghana"],
  ["GI", "350", "Gibraltar"],
  ["GR", "30", "Greece", "short_list"],
  ["GL", "299", "Greenland"],
  ["GD", "1473", "Grenada"],
  ["GP", "590", "Guadeloupe"],
  ["GU", "671", "Guam"],
  ["GT", "502", "Guatemala"],
  ["GN", "224", "Guinea"],
  ["GW", "245", "Guinea - Bissau"],
  ["GY", "592", "Guyana"],
  ["HT", "509", "Haiti"],
  ["HN", "504", "Honduras"],
  ["HK", "852", "Hong Kong", "short_list"],
  ["HU", "36", "Hungary", "short_list"],
  ["IS", "354", "Iceland", "short_list"],
  ["IN", "91", "India", "short_list"],
  ["ID", "62", "Indonesia", "short_list"],
  ["IR", "98", "Iran", "short_list"],
  ["IQ", "964", "Iraq", "short_list"],
  ["IE", "353", "Ireland", "short_list"],
  ["IL", "972", "Israel", "short_list"],
  ["IT", "39", "Italy", "short_list"],
  ["JM", "1876", "Jamaica", "short_list"],
  ["JP", "81", "Japan", "short_list"],
  ["JO", "962", "Jordan", "short_list"],
  ["KZ", "7", "Kazakhstan"],
  ["KE", "254", "Kenya"],
  ["KI", "686", "Kiribati"],
  ["KP", "850", "Korea North"],
  ["KR", "82", "Korea South", "short_list"],
  ["KW", "965", "Kuwait"],
  ["KG", "996", "Kyrgyzstan"],
  ["LA", "856", "Laos"],
  ["LV", "371", "Latvia", "short_list"],
  ["LB", "961", "Lebanon", "short_list"],
  ["LS", "266", "Lesotho"],
  ["LR", "231", "Liberia"],
  ["LY", "218", "Libya"],
  ["LI", "417", "Liechtenstein"],
  ["LT", "370", "Lithuania", "short_list"],
  ["LU", "352", "Luxembourg", "short_list"],
  ["MO", "853", "Macao"],
  ["MK", "389", "Macedonia"],
  ["MG", "261", "Madagascar"],
  ["MW", "265", "Malawi"],
  ["MY", "60", "Malaysia"],
  ["MV", "960", "Maldives"],
  ["ML", "223", "Mali"],
  ["MT", "356", "Malta"],
  ["MH", "692", "Marshall Islands"],
  ["MQ", "596", "Martinique", "short_list"],
  ["MR", "222", "Mauritania", "short_list"],
  ["YT", "269", "Mayotte"],
  ["MX", "52", "Mexico", "short_list"],
  ["FM", "691", "Micronesia"],
  ["MD", "373", "Moldova"],
  ["MC", "377", "Monaco"],
  ["MN", "976", "Mongolia"],
  ["MS", "1664", "Montserrat"],
  ["MA", "212", "Morocco", "short_list"],
  ["MZ", "258", "Mozambique"],
  ["MN", "95", "Myanmar"],
  ["NA", "264", "Namibia"],
  ["NR", "674", "Nauru"],
  ["NP", "977", "Nepal"],
  ["NL", "31", "Netherlands", "short_list"],
  ["NC", "687", "New Caledonia"],
  ["NZ", "64", "New Zealand", "short_list"],
  ["NI", "505", "Nicaragua", "short_list"],
  ["NE", "227", "Niger"],
  ["NG", "234", "Nigeria", "short_list"],
  ["NU", "683", "Niue"],
  ["NF", "672", "Norfolk Islands"],
  ["NP", "670", "Northern Marianas"],
  ["NO", "47", "Norway", "short_list"],
  ["OM", "968", "Oman"],
  ["PW", "680", "Palau", "short_list"],
  ["PA", "507", "Panama", "short_list"],
  ["PG", "675", "Papua New Guinea", "short_list"],
  ["PY", "595", "Paraguay", "short_list"],
  ["PE", "51", "Peru", "short_list"],
  ["PH", "63", "Philippines", "short_list"],
  ["PL", "48", "Poland", "short_list"],
  ["PT", "351", "Portugal", "short_list"],
  ["PR", "1787", "Puerto Rico", "short_list"],
  ["QA", "974", "Qatar", "short_list"],
  ["RE", "262", "Reunion"],
  ["RO", "40", "Romania"],
  ["RU", "7", "Russia", "short_list"],
  ["RW", "250", "Rwanda"],
  ["SM", "378", "San Marino"],
  ["ST", "239", "Sao Tome & Principe"],
  ["SA", "966", "Saudi Arabia", "short_list"],
  ["SN", "221", "Senegal"],
  ["CS", "381", "Serbia"],
  ["SC", "248", "Seychelles"],
  ["SL", "232", "Sierra Leone"],
  ["SG", "65", "Singapore", "short_list"],
  ["SK", "421", "Slovak Republic", "short_list"],
  ["SI", "386", "Slovenia", "short_list"],
  ["SB", "677", "Solomon Islands"],
  ["SO", "252", "Somalia"],
  ["ZA", "27", "South Africa", "short_list"],
  ["ES", "34", "Spain", "short_list"],
  ["LK", "94", "Sri Lanka"],
  ["SH", "290", "St. Helena"],
  ["KN", "1869", "St. Kitts"],
  ["SC", "1758", "St. Lucia"],
  ["SD", "249", "Sudan"],
  ["SR", "597", "Suriname"],
  ["SZ", "268", "Swaziland"],
  ["SE", "46", "Sweden", "short_list"],
  ["CH", "41", "Switzerland", "short_list"],
  ["SI", "963", "Syria"],
  ["TW", "886", "Taiwan", "short_list"],
  ["TJ", "7", "Tajikstan"],
  ["TH", "66", "Thailand", "short_list"],
  ["TG", "228", "Togo"],
  ["TO", "676", "Tonga"],
  ["TT", "1868", "Trinidad & Tobago", "short_list"],
  ["TN", "216", "Tunisia", "short_list"],
  ["TR", "90", "Turkey", "short_list"],
  ["TM", "7", "Turkmenistan"],
  ["TM", "993", "Turkmenistan"],
  ["TC", "1649", "Turks & Caicos Islands", "short_list"],
  ["TV", "688", "Tuvalu"],
  ["UG", "256", "Uganda"],
  ["GB", "44", "UK", "short_list"],
  ["UA", "380", "Ukraine", "short_list"],
  ["AE", "971", "United Arab Emirates", "short_list"],
  ["UY", "598", "Uruguay", "short_list"],
  ["US", "1", "USA", "short_list"],
  ["UZ", "7", "Uzbekistan"],
  ["VU", "678", "Vanuatu"],
  ["VA", "379", "Vatican City"],
  ["VE", "58", "Venezuela", "short_list"],
  ["VN", "84", "Vietnam", "short_list"],
  ["VG", "84", "Virgin Islands - British", "short_list"],
  ["VI", "84", "Virgin Islands - US", "short_list"],
  ["WF", "681", "Wallis Futuna"],
  ["YE", "969", "Yemen (North)", "short_list"],
  ["YE", "967", "Yemen (South)", "short_list"],
  ["ZM", "260", "Zambia"],
  ["ZW", "263", "Zimbabwe"]
]